#!/bin/bash
#############################################################################################
# Script to replace the contents of the following encrypted JSON entries with their defaults
#
# password    - ${p?:cics.password}
# ks_password - ${p?:cics.kspassword}
# ts_password - ${p?:cics.tspassword}
#
# See https://jqplay.org/
#
# Licensed Materials - Property of IBM.
# (c) Copyright IBM Corporation 2017. All Rights Reserved.
# US Government Users Restricted Rights
# Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corporation
#############################################################################################
FILE="${1}"
TEMP=$(mktemp)

jq -a '(.. | .password? | strings | select( . = startswith("crypt_v1"))) |= "${p?:cics.password}" | (.. | .ks_password? | strings | select( . = startswith("crypt_v1"))) |= "${p?:cics.kspassword}" | (.. | .ts_password? | strings | select( . = startswith("crypt_v1"))) |= "${p?:cics.tspassword}"' "${FILE}" > "${TEMP}"

mv "${TEMP}" "${FILE}"
